import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import Layout from "@/components/layout/layout";
import { GlobalContextProvider } from "@/context/GlobalContext";

export const metadata: Metadata = {
	title: "Sweet Plan",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<GlobalContextProvider>
					<AuthContextProvider>
						<Layout>{children}</Layout>
					</AuthContextProvider>
				</GlobalContextProvider>
			</body>
		</html>
	);
}
